recipe/meta.yaml
Depends on Distributed 1.11.0 in https://github.com/conda-forge/distributed-feedstock/pull/4.
=> Add distributed dependency

appveyor.yml, recipe/meta.yaml
Also add pitrou and mdurant as maintainers
@pitrou and @martindurant do you consent to being listed as maintainers of the dask/dask conda-forge feedstock?
=> bump version 0.14.1

recipe/meta.yaml
also add license file to meta.yaml
=> bump version to 0.14.3

recipe/meta.yaml
=> Add @jakirkham [ci skip]

recipe/meta.yaml
Here is an attempt at a metapackage.  Mostly I just removed the source section and added `dask-core` to the requirements.
cc @jakirkham
=> Bump version to 0.15.2.  Also create metapackage

recipe/meta.yaml
=> bump version to 0.17.4

recipe/meta.yaml
=> bump version to 0.18.1

recipe/meta.yaml
Checklist
Depends on PR ( https://github.com/conda-forge/dask-core-feedstock/pull/20 ).
=> Release 0.18.2

recipe/meta.yaml
=> bump version to 0.19.1

recipe/meta.yaml
=> bump version to 0.19.2

recipe/meta.yaml
=> Bump version to 0.19.3

recipe/meta.yaml
=> bump version to 0.19.4

.ci_support/linux_.yaml, .circleci/build_steps.sh, .circleci/fast_finish_ci_pr_build.sh, .circleci/run_docker_build.sh, .github/PULL_REQUEST_TEMPLATE.md, README.md, recipe/meta.yaml
=> Release 0.20.0

recipe/meta.yaml
=> bump version to 0.20.2

recipe/meta.yaml
=> Release 1.0.0

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/build_steps.sh, .azure-pipelines/run_docker_build.sh, .ci_support/linux_.yaml, .circleci/config.yml, .circleci/fast_finish_ci_pr_build.sh, README.md, azure-pipelines.yml, recipe/meta.yaml
To ensure the auto-update bot generates PRs to update the `dask` feedstock, add the source URL for the PyPI packages. That way it can detect and update this package when needed. This in spite of the fact that this is a metapackage that has no build step of its own.
Checklist
=> Add the source URL for the Dask PyPI packages

.ci_support/linux_.yaml, .github/CODEOWNERS, recipe/meta.yaml
=> bump version to 2.0.0

recipe/meta.yaml
=> Require Python 3.6 and above

recipe/meta.yaml
=> Bump minimum fsspec to 0.6.0

README.md, recipe/meta.yaml
Closes #105, closes #104
Checklist
=> dask v2.13.0

recipe/meta.yaml
Checklist
The conda-forge bot opened up a PR over in https://github.com/conda-forge/dask-feedstock/pull/127 but it appears not all CI checks ran. Trying another PR to see if CI runs
=> Bump version to 2.29.0

recipe/meta.yaml
=> Release 2021.06.1

recipe/meta.yaml
=> Release 2021.7.2

recipe/meta.yaml
Checklist
Closes https://github.com/conda-forge/dask-feedstock/pull/159
=> Release 2021.09.1

.gitattributes, .scripts/build_steps.sh, .scripts/run_docker_build.sh, README.md, build-locally.py, recipe/meta.yaml
=> Release 2021.11.0

recipe/meta.yaml
Upgrade to the latest Dask + Distributed release using grayskull. Accept some (though not all) of the changes grayskull makes. Not all of them make sense in this context.
Checklist
=> Release 2021.11.1 (with grayskull)

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .scripts/build_steps.sh, recipe/meta.yaml
Checklist
Closes https://github.com/conda-forge/dask-feedstock/issues/165
=> Release 2021.12.0

LICENSE.txt, recipe/meta.yaml
=> Release 2022.01.1

recipe/meta.yaml
=> Release 2022.02.0

recipe/meta.yaml
=> Release 2022.03.0

recipe/meta.yaml
=> Release 2022.04.0

recipe/meta.yaml
=> Release 2022.5.1

.circleci/config.yml, .scripts/build_steps.sh, LICENSE.txt, README.md, build-locally.py, recipe/meta.yaml
=> Release 2022.6.1

recipe/meta.yaml
Checklist
Fixes https://github.com/conda-forge/dask-feedstock/issues/187
=> Revert to template friendly source URL

recipe/meta.yaml
=> Add new CLI commands

recipe/meta.yaml
Checklist
This entrypoint is moving to `dask-core` (xref https://github.com/conda-forge/distributed-feedstock/pull/226#issuecomment-1286023807,  https://github.com/conda-forge/dask-core-feedstock/pull/143)
=> Remove `dask` entrypoint

.github/CODEOWNERS, README.md, recipe/meta.yaml
=> Release 2022.10.2

recipe/meta.yaml
=> Release 2023.3.2

recipe/meta.yaml
=> Release 2023.4.0

.scripts/build_steps.sh, README.md, recipe/meta.yaml
=> Release 2023.5.0

.azure-pipelines/azure-pipelines-linux.yml, recipe/meta.yaml
=> Release 2023.8.0

recipe/meta.yaml
=> Release 2023.12.0

.scripts/build_steps.sh, build-locally.py, recipe/meta.yaml
=> Release 2024.2.1

recipe/meta.yaml
=> Add fjetter to maintainers

recipe/meta.yaml
=> Release 2024.3.0

.ci_support/linux_64_.yaml, recipe/meta.yaml
=> Release 2024.7.0

.ci_support/linux_64_.yaml, recipe/meta.yaml
=> Release 2024.11.1

recipe/meta.yaml
=> Release 2024.11.2

recipe/meta.yaml
=> Release v2025.1.0

.scripts/run_docker_build.sh, build-locally.py, recipe/meta.yaml
Checklist
Closes https://github.com/conda-forge/dask-feedstock/issues/289
=> Release 2025.4.0

recipe/recipe.yaml
I was unable to merge #298 as I'm not listed as a maintainer here, adding myself now. Thanks for getting things merged in the meantime @TomAugspurger.
=> Add jacobtomlinson to maintainers

.github/CODEOWNERS, README.md, recipe/recipe.yaml
=> Update to 2025.9.1
